Repository fetch4/GISS-GC, pull requests merged in 2025-02, with the labels that each got.

#73 Improve dev utils debugging experience
  .dev/config/geoschem_config.yml
  .dev/utils/build.sh
  .dev/utils/run.sh
  .dev/utils/setup.sh
  .github/set_gcclassic_rundir.sh
  .github/workflows/compile_gcclassic.yml
  .github/workflows/compile_giss.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  exec/setup_e.pl
Labels: enhancement, testing

#72 Misc fixes for coupled setup
  .dev/config/geoschem_config.yml
  .dev/utils/build.sh
  .dev/utils/run.sh
  .dev/utils/setup.sh
  .github/set_gcclassic_rundir.sh
  .github/workflows/compile_gcclassic.yml
  .github/workflows/compile_giss.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .gitignore
  config/compiler.intel.mk
  decks/Makefile
  exec/setup_e.pl
  model/geos-chem/CMakeLists.txt
  model/geos-chem/CMakeScripts/GC-ConfigureGISS-GC.cmake
Labels: bug

#83 Fix workflow concurrency issue
  .github/workflows/compile_giss.yml
  .github/workflows/lint.yml
Labels: bug, testing

#82 Warm restart as well as cold restart
  .dev/config/geoschem_config.yml
  .dev/utils/run.sh
  .github/rundecks/GISS_GC_14.R
  .github/rundecks/GISS_ONLY.R
Labels: testing, deliverable1

#77 Use the SZA calculated by the GCM rather than that calculateed by GEOS-Chem. The latter is incorrect when using multiple CPUs.
  model/CHEM_DRV.F90
Labels: bug

#85 Various model setup tweaks
  .dev/config/geoschem_config.yml
  .github/rundecks/GISS_GC_14.R
  .github/rundecks/GISS_ONLY.R
Labels: testing, deliverable1
